# Servidor
server.port=8080
spring.application.name=rentapi

# Base de datos — Supabase (Session Pooler - IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.tsdwnrvbkimazoqnvnjc
spring.datasource.username=postgres.tsdwnrvbkimazoqnvnjc
spring.datasource.password=RentApi2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha